
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 11;
  public static final int CADENA = 18;
  public static final int IGUAL = 9;
  public static final int LETRA = 17;
  public static final int DECIMAL = 15;
  public static final int RSTRING = 26;
  public static final int RMAIN = 22;
  public static final int RINT = 23;
  public static final int UMENOS = 20;
  public static final int LLAV_IZQ = 7;
  public static final int RBOOL = 27;
  public static final int ID = 16;
  public static final int POR = 12;
  public static final int LLAV_DER = 8;
  public static final int CARACTER = 19;
  public static final int RVOID = 21;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int PAR_IZQ = 3;
  public static final int RDOUBLE = 24;
  public static final int error = 1;
  public static final int PAR_DER = 4;
  public static final int RCHAR = 25;
  public static final int COR_IZQ = 5;
  public static final int COR_DER = 6;
  public static final int ENTERO = 14;
  public static final int MAS = 10;
  public static final int PTCOMA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PAR_IZQ",
  "PAR_DER",
  "COR_IZQ",
  "COR_DER",
  "LLAV_IZQ",
  "LLAV_DER",
  "IGUAL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ENTERO",
  "DECIMAL",
  "ID",
  "LETRA",
  "CADENA",
  "CARACTER",
  "UMENOS",
  "RVOID",
  "RMAIN",
  "RINT",
  "RDOUBLE",
  "RCHAR",
  "RSTRING",
  "RBOOL"
  };
}

